language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
matrix:
  include:
    - name: "4.06"
      env: OCAML_VERSION=4.06
script: bash -ex .travis-opam.sh

env:
  global:
    - MAKEFLAGS="-j2"
cache:
  directories:
    - /home/travis/.opam/
