language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh; bash -ex .travis-opam.sh; opam install -y menhir oUnit
script: make test
env:
  - OCAML_VERSION=4.06
