on: [push, pull_request]
name: CI
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Set up OPAM
      run: |
        sudo apt-get update
        sudo apt-get install -y opam
        opam init --yes
        eval `opam config env`
        opam --version

    - name: Set up OCaml
      run: |
        opam switch install 4.07.0
        eval `opam config env`
        ocaml -version

    - name: Install dependencies
      run: |
        opam pin add github-actions-ci-repo `pwd` --no-action --yes
        opam install github-actions-ci-repo --deps-only --yes

    - name: Run tests
      run: make test
